# Generated by Django 6.0.5 on 2026-06-01 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_happened',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 1, 14, 4, 40, 590333, tzinfo=datetime.timezone.utc)),
        ),
    ]
