# Generated by Django 6.0.5 on 2026-06-01 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_date_happened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_happened',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
