# Generated by Django 6.0.5 on 2026-06-02 06:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
